apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-engineering
  description: IDP(Internal Developer Platform) & Platform Engineering
  annotations:
    github.com/project-slug: https://github.com/sunghwan-joo/platform-engineering.git
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: sunghwan.joo@example.com
  lifecycle: experimental
